version: "3.7"

services:
  backend:
    build: ./back_end
    ports:
      - "8000:8000"

  frontend:
    build: ./front_end
    ports:
      - "3000:3000"
# ==============End==============

# --------Command line---------

